# Generated by Django 3.1.6 on 2021-02-15 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 11, 53, 36, 984282), verbose_name='date published'),
        ),
    ]
