# Generated by Django 3.1.6 on 2021-02-15 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210215_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 13, 45, 10, 293639), verbose_name='date published'),
        ),
    ]
