# Generated by Django 3.1.6 on 2021-02-15 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210215_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 14, 9, 32, 562742), verbose_name='date published'),
        ),
    ]
